SharpSeer/Models/Teacher.cs
using System;
using System.Collections.Generic;

namespace SharpSeer.Models;

public partial class Teacher
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string? PhoneNumber { get; set; }

    public string NameId { get; set; } = null!;

    public bool? IsExternal { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}

SharpSeer/Pages/Teachers/Teacher_Page.cshtml.cs
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SharpSeer.Interfaces;
using SharpSeer.Models;

namespace SharpSeer.Pages.Teachers
{
    public class Teacher_PageModel : PageModel
    {
        public bool ShowDelete { get; set; } = false;
        public bool ShowUpdate { get; set; } = false;
        public bool ShowCreate { get; set; } = false;
        [BindProperty(SupportsGet = true)]
        public string Email { get; set; }
        [BindProperty(SupportsGet = true)]
        public string PhoneNumber { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool IsTeacher { get; set; }

        [BindProperty(SupportsGet = true)]
        public string NameId { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool? IsExternal { get; set; }

        [BindProperty(SupportsGet =true)]
        public string QueryString { get; set; } = string.Empty;

        [BindProperty(SupportsGet =true)] 
        public Teacher? Teacher { get; set; }

        public IEnumerable<Teacher> Teachers { get; set; }
        private IService<Teacher> m_service;
        public Teacher_PageModel(IService<Teacher> service)
        {
            m_service = service;
            Teachers = m_service.GetAll();
            Teacher = new Teacher();
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void GetQueryValues(in string q)
        {
            HttpContext.Request.Query.TryGetValue(q, out var value);
            Teacher = m_service.GetById(int.Parse(value));
        }

       
        public void OnGet()
        {

            if (Request.Cookies.ContainsKey("IsTeacher"))
            {
                var cookie = Request.Cookies["IsTeacher"];
                if (!string.IsNullOrEmpty(cookie))
                {
                    IsTeacher = cookie == "true";
                }
            }

            ICollection<string> QKeys = HttpContext.Request.Query.Keys;
            foreach (var q in QKeys)
            {
                switch (q)
                {
                    case "Delete":
                        ShowDelete = true;
                        GetQueryValues(q);
                        goto EndOfLoop;
                    case "Create":
                        ShowCreate = true;
                        HttpContext.Request.Query.TryGetValue(q, out var value);
                        QueryString = q;
                        goto EndOfLoop;
                    case "Update":
                        ShowUpdate = true;
                        GetQueryValues(q);
                        goto EndOfLoop;
                    case "Name":
                        if (!string.IsNullOrEmpty(Name))
                        { 
                            Teachers = Teachers.Where(t => t.Name.Contains(Name, StringComparison.OrdinalIgnoreCase));
                        }
                        break;
                    case "Email":
                        if (!string.IsNullOrEmpty(Email))
                        {
                            Teachers = Teachers.Where(t => t.Email.Contains(Email, StringComparison.OrdinalIgnoreCase));
                        }
                       break;
                    case "PhoneNumber":
                        if (!string.IsNullOrEmpty(PhoneNumber))
                        {
                            Teachers = Teachers.Where(t => t.PhoneNumber.Contains(PhoneNumber, StringComparison.OrdinalIgnoreCase));
                        }
                        break;
                    case "NameId":
                        if (!string.IsNullOrEmpty(NameId))
                        {
                            Teachers = Teachers.Where(t => t.NameId.Contains(NameId, StringComparison.OrdinalIgnoreCase));
                        }
                        break;
                    case "IsExternal":
                        if (IsExternal.HasValue)
                        {
                            Teachers = Teachers.Where(t => t.IsExternal == IsExternal.Value);
                        }
                        break;
                }
            }
            EndOfLoop:;
        }
        public IActionResult OnPostDelete(int id)
        {
            Teacher.Id = id;
            m_service.Delete(Teacher);
            return RedirectToPage("Teacher_Page");
        }
        public IActionResult OnPostUpdate(int id)
        {
            Teacher.Id = id;
            m_service.Update(Teacher);
            return RedirectToPage("Teacher_Page");
        }

        public IActionResult OnPostCreate()
        {
            m_service.Create(Teacher);
            return RedirectToPage("Teacher_Page");
        }

    }
}
    

SharpSeer/Pages/Teachers/Teacher_Page.cshtml
@page 
@using SharpSeer.Models
@model SharpSeer.Pages.Teachers.Teacher_PageModel
@{
}
<h2>Lærer oversigt</h2>

@if (Model.IsTeacher == true)
{
	<a class="btn btn-primary" href="/Teachers/Teacher_Page/?Create=0">Tilføj</a>
}

<form method="get" class="search-form">
	<table class="table table-search">
		<thead>
			<tr>
				<th><input type="text" class="form-control" asp-for="Name" placeholder="Navn" /></th>
				<th><input type="text" class="form-control" asp-for="NameId" placeholder="Initialer" /></th>
				<th><input type="text" class="form-control" asp-for="Email" placeholder="E-mail" /></th>
				<th><input type="text" class="form-control" asp-for="PhoneNumber" placeholder="Telefon nummer" /></th>
				<th>
					<select asp-for="IsExternal" class="form-select">
						<option value="">Alle</option>
						<option value="true">Ja</option>
						<option value="false">Nej</option>
					</select>
				</th>
				<th>
					<button type="submit" class="btn btn-search">Søg</button>
				</th>
			</tr>
		</thead>
	</table>
</form>


<table class="table table-showup">
	<thead>
		<tr>
			<th>Navn</th>
			<th>Initialer</th>
			<th>E-mail</th>
			<th>Telefon nummer</th>
			<th>Er censor?</th>
			  <th></th>
			  <th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var teacher in Model.Teachers)
		{
			<tr>
				<td>@teacher.Name</td>
				<td>@teacher.NameId</td>
				<td>@teacher.Email</td>
				<td>@teacher.PhoneNumber</td>
				<td>@(teacher.IsExternal == true ? "Ja" : teacher.IsExternal == false ? "Nej" : "")</td>
				@if (Model.IsTeacher == true)
				{
				<td><a href="/Teachers/Teacher_Page/?Update=@teacher.Id" class="btn btn-primary">Opdater</a></td>
				<td><a href="/Teachers/Teacher_Page/?Delete=@teacher.Id" class="btn btn-danger">Slet</a></td>
				}
				else
				{
					<td></td>
					<td></td>
				}
			</tr>
		}
	</tbody>
</table>

@if (Model.ShowDelete && Model.IsTeacher == true)
{
	
	<!-- Modal -->
	<div style="display: block;" class="modal" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">Er du sikker på du vil slette denne Lærer</h4>
					<a href="/Teachers/Teacher_Page" type="button" class="btn btn-close"></a>
				</div>
				<!-- Modal body -->
				<div class="modal-body">
					@Model.Teacher.Name
				</div>
				<!-- Modal footer -->
				<div class="modal-footer">
					<form method="post" asp-route-id="@Model.Teacher.Id" asp-page-handler="Delete">
						<button type="submit" class="btn btn-danger">Ja</button>
					</form>
					<a href="/Teachers/Teacher_Page" type="button" class="btn btn-primary">Nej</a>
				</div>
			</div>
		</div>
	</div>
}

@if (Model.ShowCreate && Model.IsTeacher == true)
{
	<!-- Modal -->
	<div style="display: block;" class="modal" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">Tilføj ny lærer</h4>
					<a href="/Teachers/Teacher_Page" type="button" class="btn btn-close"></a>
				</div>
				<!-- Modal body -->
				<form method="post" asp-page-handler="Create">
					<div class="modal-body">
						<table class="table">
							<tbody>
								<tr>
									<th scope="col">
										Navn
									</th>
									<td>
										<input asp-for="Teacher.Name" class="form-control" required />
									</td>
								</tr>
								<tr>
									<th scope="col">
										Navne kode
									</th>
									<td>
										<input asp-for="Teacher.NameId" class="form-control" required />
									</td>
								</tr>
								<tr>
									<th scope="col">
										E-Mail
									</th>
									<td>
										<input asp-for="Teacher.Email" class="form-control" required />
									</td>
								</tr>
								<tr>
									<th scope="col">
										Telefon nummer
									</th>
									<td>
										<input asp-for="Teacher.PhoneNumber" class="form-control" required />
									</td>
								<tr>
									<th scope="col">
										Extern censor
									</th>
									<td>
										<select asp-for="Teacher.IsExternal" class="form-select">
											<option value="false">Nej</option>
											<option value="true">Ja</option>
										</select>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<!-- Modal footer -->
					<div class="modal-footer">

						<button type="submit" class="btn btn-primary">Godkend</button>
						<a href="/Teachers/Teacher_Page" type="button" class="btn btn-danger">Annuller</a>
					</div>
				</form>
			</div>
		</div>
	</div>
}

@if (Model.ShowUpdate && Model.IsTeacher == true)
{
	<!-- Modal -->
	<div style="display: block;" class="modal" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">Opdater hold</h4>
					<a href="/Teachers/Teacher_Page" type="button" class="btn btn-close"></a>
				</div>
				<!-- Modal body -->
				<form method="post" asp-route-id="@Model.Teacher.Id" asp-page-handler="Update">
					<div class="modal-body">
						<table class="table">
							<tbody>
								<tr>
									<th scope="col">
										Navn
									</th>
									<td>
										<input asp-for="Teacher.Name" class="form-control" />
									</td>
								</tr>
								<tr>
									<th scope="col">
										Navne kode
									</th>
									<td>
										<input asp-for="Teacher.NameId" class="form-control" />
									</td>
								</tr>	
								<tr>
									<th scope="col">
										E-Mail
									</th>
									<td>
										<input asp-for="Teacher.Email" class="form-control" />
									</td>
								</tr>
								<tr>
									<th scope="col">
										Telefon nummer
									</th>
									<td>
										<input asp-for="Teacher.PhoneNumber" class="form-control" />
									</td>
								</tr>
								<tr>
									<th scope="col">
										Extern censor
									</th>
									<td>
										<select asp-for="Teacher.IsExternal" class="form-select">
											<option value="false">Nej</option>
											<option value="true">Ja</option>
										</select>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<!-- Modal footer -->
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary">Opdater</button>
						<a href="/Teachers/Teacher_Page" type="button" class="btn btn-danger">Annuller</a>
					</div>
				</form>
			</div>
		</div>
	</div>
}

<body class="background">
</body>





@section Scripts
{
	<script>
		$(document).ready(function () {
			$("#myModal").modal({backdrop: "static"});
			$("#myModal").modal("show");
		});)
	</script>
}