SharpSeer/Pages/Calendar/CalendarView.cshtml.cs
using System.Collections;
using System.Reflection.Metadata.Ecma335;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Identity.Client;
using SharpSeer.Interfaces;
using SharpSeer.Models;
using SharpSeer.Services;
using System.IO;
using Microsoft.IdentityModel.Tokens;
using SharpSeer;
using System.Runtime.CompilerServices;

namespace MyApp.Namespace
{
    public class CalendarViewModel : PageModel
    {
        public LinkedList<Exam> ExamButtons { get; set; }
        [BindProperty (SupportsGet = true)]
        public List<int> CohortsID { get; set; }
        [BindProperty (SupportsGet = true)]
        public List<int> TeachersID { get; set; }
        public IEnumerable<Teacher> Teachers { get; set; }
        public IEnumerable<Cohort> Cohorts { get; set; }
        [BindProperty]
        public int ExamButtonIndex { get; set; } = 0;
        public DateTime CurrentTime { get; set; } = DateTime.Now;
        public DateTime LastDateInMonth { get; set; }
		private DateTime m_selectedDateTime;
        [BindProperty (SupportsGet = true)]
        public CustomDateOnly SelectedDateTime { get; set; }
        public int DaysInMonth { get; set; } = 0;
        public int Year { get; set; } = 0;
        public int Month { get; set; } = 0;
        public string MonthStr { get; set; } = "";
        public int FirstDayOfMonth { get; set; } = 0;
        public List<string> WeekNames { get; set; }
        public string UpdateModal { get; set; } = "";
        [BindProperty (SupportsGet = true)]
        public bool? IsTeacher { get; set; } = null;
        [BindProperty (SupportsGet = true)]
        public Exam? SelectedExam { get; set; } = new Exam();
        [BindProperty]
        public Exam.ExamTypeEnum ExamType { get; set; }
        public bool ShowUpdate { get; set; } = false;
        public bool ShowSelected { get; set; } = false;
        private SharpSeerDbContext m_context;

        public IEnumerable<Cohort> CohortsAll { get; set; }
        public IEnumerable<Teacher> TeachersAll { get; set; }
        [BindProperty(SupportsGet = true)]
        public bool? IsGuarded { get; set; } = null;
        [BindProperty(SupportsGet = true)]
        public bool? NeedExternalExaminer { get; set; } = null;
        private IService<Exam> m_service;
        private IService<Teacher> m_teacherService;
        private IService<Cohort> m_cohortService;
        [BindProperty (SupportsGet = true)]
        public int TeacherID { get; set; }
        public Teacher? SelectedTeacher { get; set; }
        public Cohort? SelectedCohort { get; set; }
        public HashSet<int> OverlappingExams { get; set; } = new HashSet<int>();
        public List<Tuple<Exam, Teacher>>? OverlappingTeacher { get; set; } = null;
        public List<Tuple<Exam, Cohort>>? OverlappingCohort { get; set; } = null;
        public string OverlappingStr { get; set; } = "";
        public string ExamColor { get; set; } = "exam";
        public string ExamDisplayName { get; set; } = "";

        public CalendarViewModel(SharpSeerDbContext dbContext, IService<Exam> service, IService<Cohort> cohortService, IService<Teacher> teacherService)
        {
            m_service = service;
            Year = CurrentTime.Year;
            Month = CurrentTime.Month;
            WeekNames = new List<string>{"Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag", "Lørdag", "Søndag"};
            m_context = dbContext;
            m_cohortService = cohortService;
            m_teacherService = teacherService;
        }
        public IActionResult OnGet()
        {
            ICollection<string> QKeys = HttpContext.Request.Query.Keys;
            try
            {
                foreach (string key in QKeys)
                {
                    if (key == "month")
                    {
                        HttpContext.Request.Query.TryGetValue(key, out var month);
                        if (!month.IsNullOrEmpty())
                        {
                            Month = int.Parse(month!);
                        }
                        continue;
                    }
                    if (key == "year")
                    {
                        HttpContext.Request.Query.TryGetValue(key, out var year);
                        if (!year.IsNullOrEmpty())
                        {
                            Year = int.Parse(year!);
                        }
                        continue;
                    }
                }
            }
            catch (FormatException)
            {
                Month = CurrentTime.Month;
                Year = CurrentTime.Year;

                return RedirectToPage(new
                {
                    month = Month,
                    year = Year
                });
            }

            GetMonth();
			GetDataFromDatabase();
            SetJunctionTable();
            GetOverlapping();

            return Page();
        }

        public void OnPostGetTeacher(int teacherID, int month, int year)
        {
            Month = month;
            Year = year;
            SelectedTeacher = m_teacherService.GetById(teacherID);
            Cohorts = m_cohortService.GetAll();
            Teachers = m_teacherService.GetAll();
            List<Teacher> teachers = new List<Teacher>(Teachers);
            int teacherToBeSwaped = teachers.FindIndex(t => t.Id == teacherID);
            teachers.RemoveAt(teacherToBeSwaped);
            Teachers = teachers.Prepend(SelectedTeacher);
            
            GetMonth();
            LastDateInMonth = new DateTime(Year, Month, DaysInMonth);
			IEnumerable<Exam> buttons = m_context.Exams.Include(e => e.Cohorts)
                .Include(e => e.Teachers).Where(e => e.FirstExamDate <= LastDateInMonth && e.LastExamDate >= m_selectedDateTime && e.Teachers.Any<Teacher>(t => t.Id == TeacherID))
                .OrderBy(e => e.FirstExamDate);
			ExamButtons = new LinkedList<Exam>(buttons);
        }

        public void OnPostGetCohort(int cohortID, int month, int year)
        {
            Month = month;
            Year = year;
            SelectedCohort = m_cohortService.GetById(cohortID);
            Cohorts = m_cohortService.GetAll();
            Teachers = m_teacherService.GetAll();
            List<Cohort> cohorts = new List<Cohort>(Cohorts);
            int cohortToBeSwaped = cohorts.FindIndex(c => c.Id == cohortID);
            cohorts.RemoveAt(cohortToBeSwaped);
            Cohorts = cohorts.Prepend(SelectedCohort);

            GetMonth();
            LastDateInMonth = new DateTime(Year, Month, DaysInMonth);
			IEnumerable<Exam> buttons = m_context.Exams.Include(e => e.Cohorts)
                .Include(e => e.Teachers).Where(e => e.FirstExamDate <= LastDateInMonth && e.LastExamDate >= m_selectedDateTime && 
                e.Cohorts.Any<Cohort>(t => t.Id == cohortID)).OrderBy(e => e.FirstExamDate);
			ExamButtons = new LinkedList<Exam>(buttons);
        }
     
        public IActionResult OnPostUpdate(int id, int month, int year)
        {
            Month = month;
            Year = year;
            SelectedExam.Id = id;
            SelectedExam.ExamType = (int)ExamType;

            if (IsGuarded.HasValue)
            {
                SelectedExam.IsGuarded = IsGuarded.Value;
            }
            if (NeedExternalExaminer.HasValue)
            {
                SelectedExam.NeedExternalExaminer = NeedExternalExaminer.Value;
            }
            
            foreach (var cohortId in CohortsID)
            {
                var cohort = m_cohortService.GetById(cohortId);
                SelectedExam.Cohorts.Add(cohort);
            }
            foreach (var teacherId in TeachersID)
            {
                var teacher = m_teacherService.GetById(teacherId);
                SelectedExam.Teachers.Add(teacher);
            }

            GetOverlapping();

            // List<Exam> exams = m_service.GetAll().Where(e => e.LastExamDate >= SelectedExam.FirstExamDate && e.FirstExamDate <= SelectedExam.LastExamDate).ToList();
            m_service.Update(SelectedExam);
            return Redirect($"/Calendar/CalendarView?month={Month}&year={Year}");
        }

        public IActionResult OnPostNextMonth(int month, int year)
        {
            Month = month + 1;
            Year = year;
            if (Month > 12)
            {
                Month = 1;
                Year = year + 1;
            }

            return RedirectToPage(new 
            {
                month = Month,
                year = Year
            });
        }

        public IActionResult OnPostPreviousMonth(int month, int year)
        {
            Month = month - 1;
            Year = year;
            if (Month < 1)
            {
                Month = 12;
                Year = year - 1;
            }

            return RedirectToPage(new 
            {
                month = Month,
                year = Year
            });
        }

        private void GetMonth()
        {
            DaysInMonth = DateTime.DaysInMonth(Year, Month);
            m_selectedDateTime = new DateTime(Year, Month, 1);
            SelectedDateTime = new CustomDateOnly(m_selectedDateTime);
            DayOfWeek dayOfWeek = m_selectedDateTime.DayOfWeek;
            FirstDayOfMonth = GetDayOfWeekAsNumber(dayOfWeek.ToString());
            MonthStr = GetMonthName(Month);
        }

		public void GetDataFromDatabase()
		{
			LastDateInMonth = new DateTime(Year, Month, DaysInMonth);
			IEnumerable<Exam> buttons = m_context.Exams.Include(e => e.Cohorts)
                .Include(e => e.Teachers).Where(e => e.FirstExamDate <= LastDateInMonth && e.LastExamDate >= m_selectedDateTime)
                .OrderBy(e => e.FirstExamDate);
			ExamButtons = new LinkedList<Exam>(buttons);
		}

        public void OnPostSelectedExam(int examID, int month, int year)
        {

SharpSeer/Pages/Calendar/CalendarView.cshtml
@page
@using Microsoft.VisualBasic
@using MyApp.Namespace
@using SharpSeer.Models
@model MyApp.Namespace.CalendarViewModel
@{
}


<body class="background">

	<h1> Kalender oversigt </h1>

	<div class="calendar-filter">
		<form method="post" asp-page-handler="GetTeacher" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
			<select id="teacher" name="TeacherID">
				@foreach (Teacher teacher in Model.Teachers)
				{
					<option value="@teacher.Id">@teacher.Name</option>
				}
			</select>
			<button type="submit">vælg</button>
		</form>

		<form method="post" asp-page-handler="GetCohort" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
			<select id="cohort" name="CohortID">
				@foreach (Cohort cohort in Model.Cohorts)
				{
					<option value="@cohort.Id">@cohort.Name</option>
				}
			</select>

			<button type="submit">vælg</button>
		</form>
	</div>


	<h1></h1>

	<div class="month">
  <ul>
    <form method="post" asp-page-handler="PreviousMonth" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
        <li class="prev">
            <button type="submit">&#10094;</button>
        </li>
    </form>
    <form method="post" asp-page-handler="NextMonth" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
        <li class="next">
        <button type="submit">&#10095;</button>
        </li>
    </form>
    <li>
      @Model.MonthStr<br>
      <span style="font-size:40px">@Model.Year</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  @foreach (string day in Model.WeekNames)
  {
    <li>@day</li>
  }
</ul>

<ul class="days">
  @for (int i = 1; i < Model.FirstDayOfMonth; i++)
  {
    <li class="empty"></li>
  }
  
  @for (int day = 1; day <= Model.DaysInMonth; day++)
  {
		{Model.UpdateDateTime(day);}
	
    <li>@day
        @foreach (Models.Exam exam in Model.ExamButtons)
        {
            if (Model.SelectedDateTime.Comparer(exam.LastExamDate) == -1)
            {
                continue;
            }
            
            if (Model.SelectedDateTime.Comparer(exam.FirstExamDate) == -1 || Model.SelectedDateTime.Comparer(exam.FirstExamDate) == 0 
            && Model.SelectedDateTime.Comparer(exam.LastExamDate) == 1 || Model.SelectedDateTime.Comparer(exam.LastExamDate) == 0)
            {
                <form method="post" asp-page-handler="SelectedExam" asp-route-examID="@exam.Id" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
                    <div>
						@if (Model.OverlappingExams.Contains(exam.Id))
						{
							{Model.GetExamType(exam);}
							<button type="submit" class="btn danger @Model.ExamColor">@Model.ExamDisplayName</button>
						}
						else
						{
							{Model.GetExamType(exam);}
							<button type="submit" class="btn @Model.ExamColor">@Model.ExamDisplayName</button>
						}
                    </div>
                </form>
            }
        }
    </li>
  }
</ul> 

	@if (Model.ShowUpdate)
	{

		<!-- Modal -->
		<div style="display: block;" class="modal modal-lg" id="myModal">
			<div class="modal-dialog">
				<div class="modal-content">
					<!-- Modal Header -->
					<div class="modal-header">
						<h4 class="modal-title">Opdater eksamen</h4>
						<a href="/Calendar/CalendarView" type="button" class="btn btn-close"></a>
					</div>
					<!-- Modal body -->
					<div class="modal-body">
						<table class="table">
							<thead>
								<tr>
									<th></th>
									<th>
										Information
									</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<th scope="col">
										Navn
									</th>
									<td>
										@Model.SelectedExam.Name
									</td>
								</tr>
								<tr>
									<th scope="col">
										Eksamens type
									</th>
									<td>
										@((Exam.ExamTypeEnum)Model.SelectedExam.ExamType)
									
									</td>
								</tr>
								<tr>
									<th scope="col">
										Hold
									</th>
									<td scope="col">
										@((Model.SelectedExam.Cohorts?.Any() ?? false)
																				? string.Join(", ", Model.SelectedExam.Cohorts.Select(c => c.Name)) : "Ingen hold tilknyttet")
									</td>
								</tr>
								<tr>
									<th scope="col">
										Underviser(e)
									</th>
									<td scope="col">
										@((Model.SelectedExam.Teachers?.Any() ?? false)
																				? string.Join(", ", Model.SelectedExam.Teachers.Select(t => t.Name)) : "Ingen underviser tilknyttet")
										</td>
									</tr>
									<tr>
										<th scope="col">
											Med vagt
										</th>
										<td>
											@(Model.SelectedExam.IsGuarded ? "Ja" : "Nej")
										</td>
									</tr>

									<tr>
										<td>Ekstern censor</td>
										<td>@(Model.SelectedExam.NeedExternalExaminer ? "Ja" : "Nej")</td>
									</tr>

									<tr>
										<td>Eksamens start</td>
										<td>@Model.SelectedExam.FirstExamDate</td>
									</tr>

									<tr>
										<td>Eksamens slut</td>
										<td>@Model.SelectedExam.LastExamDate</td>
									</tr>

									<tr>
										<td>Deadline for aflevering</td>
										<td>@Model.SelectedExam.HandInDeadline</td>
									</tr>

									<tr>
										<td>Eksamens varighed (minutter)</td>
										<td>@Model.SelectedExam.DurationInMinutes</td>
									</tr>
								</tbody>
							</table>
						</div>
				</div>
			</div>
		</div>
	}


@if (Model.ShowUpdate && Model.IsTeacher == true)
{
	
	<!-- Modal -->
	<div style="display: block;" class="modal modal-lg" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">Opdater eksamen</h4>
					<a href="/Calendar/CalendarView" type="button" class="btn btn-close"></a>
				</div>
				<!-- Modal body -->
				@if (Model.OverlappingStr != string.Empty)
				{
					<div class="overlappingBox">
						<div>Overlap</div>
						<div style="color: #ee1a1a;">
							@Model.OverlappingStr
						</div>
					</div>
				}
			
				<form method="post" asp-page-handler="Update" asp-route-id="@Model.SelectedExam.Id" asp-route-month="@Model.Month" asp-route-year="@Model.Year">
				<div class="modal-body">
					<table class="table">
						<thead>
							<tr>
								<th></th>
								<th>
									Oprindelig information
								</th>
								<th>
									Opdateret information
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th scope="col">
									Navn
								</th>
								<td>
									@Model.SelectedExam.Name
								</td>
								<td>
									<input asp-for="SelectedExam.Name" class="form-control" />
								</td>
							</tr>
							<tr>
								<th scope="col">
									Eksamens type
								</th>
								<td>
									@((Exam.ExamTypeEnum)Model.SelectedExam.ExamType)
								</td>
								<td>
									<select asp-for="ExamType" asp-items="@Html.GetEnumSelectList<Exam.ExamTypeEnum>()" class="form-select">
									</select>
								</td>
								
							</tr>
							<tr>
								<th scope="col">
									Hold
								</th>
								<td scope="col">
									@((Model.SelectedExam.Cohorts?.Any() ?? false)
											? string.Join(", ", Model.SelectedExam.Cohorts.Select(c => c.Name)) : "Ingen hold tilknyttet")
								</td>
								<td>
										<div style="height:80px;overflow-y:scroll">
										@foreach (var cohort in Model.CohortsAll)
											{
												<input class="form-check-inline" name="CohortsID" type="checkbox" value="@cohort.Id" @(Model.CohortsID != null && Model.CohortsID.Contains(cohort.Id) ? "checked" : "") />
												@cohort.Name
												<br />
											}
									</div>
								</td>

							</tr>
							<tr>
								<th scope="col">
									Underviser(e)
								</th>
								<td scope="col">
									@((Model.SelectedExam.Teachers?.Any() ?? false)
										? string.Join(", ", Model.SelectedExam.Teachers.Select(t => t.Name)) : "Ingen underviser tilknyttet")
								</td>
								<td>
									@foreach (var teacher in Model.TeachersAll)
										{
											<input class="form-check-inline" name="TeachersID" type="checkbox" value="@teacher.Id" @(Model.TeachersID != null && Model.TeachersID.Contains(teacher.Id) ? "checked" : "") />
											@teacher.Name
											<br />
										}
								</td>
							</tr>
							<tr>
								<th scope="col">
									Med vagt
								</th>
								<td>
										@(Model.SelectedExam.IsGuarded  ? "Ja" : "Nej")
                                </td>
								<td>
										<select asp-for="SelectedExam.IsGuarded" class="form-select">
											<option value="true">Ja</option>
											<option value="false">Nej</option>
										</select>
									</td>
								</tr>

								<tr>
									<td>Ekstern censor</td>
									<td>@(Model.SelectedExam.NeedExternalExaminer ? "Ja" : "Nej")</td>
									<td>
										<select asp-for="SelectedExam.NeedExternalExaminer" class="form-select">
											<option value="true">Ja</option>
											<option value="false">Nej</option>
										</select>
									</td>
								</tr>

								<tr>
									<td>Eksamens start</td>
									<td>@Model.SelectedExam.FirstExamDate</td>
									<td>
										<input asp-for="SelectedExam.FirstExamDate" class="form-control" />
									</td>
								</tr>

								<tr>
									<td>Eksamens slut</td>
									<td>@Model.SelectedExam.LastExamDate</td>
									<td>
										<input asp-for="SelectedExam.LastExamDate" class="form-control" />
									</td>
								</tr>

								<tr>
									<td>Deadline for aflevering</td>
									<td>@Model.SelectedExam.HandInDeadline</td>
									<td>
										<input asp-for="SelectedExam.HandInDeadline" class="form-control" />
									</td>
								</tr>

								<tr>
									<td>Eksamens varighed (minutter)</td>
									<td>@Model.SelectedExam.DurationInMinutes</td>
									<td>
										<input asp-for="SelectedExam.DurationInMinutes" class="form-control" />
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				<!-- Modal footer -->
				<div class="modal-footer">
					
					<button type="submit" class="btn btn-primary">Opdater</button>
					<a href="/Calendar/CalendarView?month=@Model.Month&year=@Model.Year" type="button" class="btn btn-danger">Annuller</a>
				</div>
				</form>
			</div>
		</div>
	</div>
}



@section Scripts 
{
	<script>
		$(document).ready(function () {
			$("#myModal").modal({backdrop: "static"});
			$("#myModal").modal("show");
		});)
	</script>	
}

</body>